using System.Diagnostics;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;

namespace CommandDeck.Controls;

/// <summary>
/// Base <see cref="UserControl"/> for modal search overlays (CommandPalette, BranchSelector).
/// Encapsulates the three shared behaviours without requiring a shared interface on the
/// ViewModels, avoiding coupling between the Controls and ViewModels layers:
/// <list type="bullet">
///   <item>Auto-focus on the named <c>SearchBox</c> element when the control becomes visible.</item>
///   <item>Keyboard dispatch: Esc → CloseCommand, Enter → ConfirmCommand, Up/Down → navigation.</item>
///   <item>Dim-layer click → CloseCommand.</item>
/// </list>
/// The DataContext is accessed via reflection so that <c>IRelayCommand</c> / <c>IAsyncRelayCommand</c>
/// properties generated by CommunityToolkit source generators satisfy the <c>ICommand</c> call
/// without introducing an explicit interface contract on the ViewModels.
/// </summary>
public abstract class SearchOverlayControlBase : UserControl
{
    protected SearchOverlayControlBase()
    {
        IsVisibleChanged += OnIsVisibleChanged;
    }

    // ─── helpers ────────────────────────────────────────────────────────────

    private TextBox? SearchBoxElement => FindName("SearchBox") as TextBox;

    private void ExecuteCommand(string commandPropertyName)
    {
        if (DataContext is null) return;
        var prop = DataContext.GetType()
            .GetProperty(commandPropertyName, BindingFlags.Public | BindingFlags.Instance);
        if (prop is null)
        {
            Debug.WriteLine($"[SearchOverlayBase] Command not found: {commandPropertyName} on {DataContext?.GetType().Name}");
            return;
        }
        if (prop.GetValue(DataContext) is ICommand cmd)
            cmd.Execute(null);
    }

    // ─── shared handlers ────────────────────────────────────────────────────

    private void OnIsVisibleChanged(object sender, DependencyPropertyChangedEventArgs e)
    {
        if (e.NewValue is true)
        {
            // Defer focus so the visual tree is fully ready
            Dispatcher.BeginInvoke(System.Windows.Threading.DispatcherPriority.Input, () =>
            {
                var box = SearchBoxElement;
                if (box is null) return;
                box.Clear();
                box.Focus();
                Keyboard.Focus(box);
            });
        }
    }

    protected void OnKeyDown(object sender, KeyEventArgs e)
    {
        switch (e.Key)
        {
            case Key.Escape:
                ExecuteCommand("CloseCommand");
                e.Handled = true;
                break;
            case Key.Enter:
                ExecuteCommand("ConfirmCommand");
                e.Handled = true;
                break;
            case Key.Down:
                ExecuteCommand("MoveDownCommand");
                e.Handled = true;
                break;
            case Key.Up:
                ExecuteCommand("MoveUpCommand");
                e.Handled = true;
                break;
        }
    }

    protected void OnDimLayerClick(object sender, MouseButtonEventArgs e)
    {
        ExecuteCommand("CloseCommand");
    }
}
